# ---- All project specifications ---- #
[project]
name = "torchtitan"
description = "A PyTorch native platform for training generative AI models"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    { name = "PyTorch Team", email = "packages@pytorch.org" },
]
keywords = ["pytorch", "training", "llm"]
dependencies = [
    # PyTorch nightly (pinned to known working versions)
    "torch==2.11.0.dev20260129+cu130",
    "torchvision==0.25.0.dev20260129+cu130",
    "torchao==0.16.0.dev20260129+cu130",
    # Stateful Dataloader
    "torchdata>=0.8.0",
    # Hugging Face integrations
    "datasets>=3.6.0",
    # Tokenization
    "tokenizers>=0.15.0",
    # Miscellaneous
    "tomli>=1.1.0",
    "fsspec",
    "tyro",
    "tensorboard",
    "einops",
    "pillow",
    "av>=16.0.1",
    "transformers>=4.51.1",
    "diffusers>=0.36.0",
    "sentencepiece>=0.2.1",
    "torchmetrics>=1.8.2",
    "decord2>=2.0.0",
    "tomli>=1.1.0 ; python_full_version < '3.11'",
    "tabulate>=0.9.0",
    "wandb>=0.24.1",
    "safetensors>=0.7.0",
    "expecttest==0.1.6",
    "pytest==7.3.2",
    "pytest-cov>=7.0.0",
    "pre-commit>=4.5.1",
    "pyrefly==0.45.1",
    "tomli-w>=1.1.0",
]
dynamic = ["version"]

[project.urls]
GitHub = "https://github.com/pytorch/torchtitan"
Documentation = "https://github.com/pytorch/torchtitan/tree/main/docs"
Issues = "https://github.com/pytorch/torchtitan/issues"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
    "pytest-cov",
    "wandb",
    "tomli_w", # test_job_config
    "expecttest", # test_tokenizer
]

[tool.setuptools.dynamic]
version = {file = "assets/version.txt"}

[tool.codespell]
skip = ["*.json"]
ignore-words-list = ["assertin", "datas" ,"indx", "inpt", "nd", "socio-economic"]

# ---- Explicit project build information ---- #
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [""]
include = ["torchtitan*"]

[tool.pytest.ini_options]
addopts = ["--showlocals"]  # show local variables in tracebacks
testpaths = ["tests"]

[tool.uv]
index-strategy = "unsafe-first-match"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch-nightly"
url = "https://download.pytorch.org/whl/nightly/cu130"

[tool.pyrefly]
project-excludes = ["torchtitan/experiments", "**/tests/**"]
ignore-missing-imports = ["torchao.*", "torchft"]  # optional dependencies
search-path = ["../pytorch"]  # local built pytorch
